spring.application.name=event-space-api

spring.datasource.url=jdbc:oracle:thin:@//192.168.1.69:1521/FREEPDB1
spring.datasource.username=hya
spring.datasource.password=StrongPassword123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.default_schema=HYA

server.port=8080